services:
  axon-server:
    image: docker.axoniq.io/axoniq/axonserver:2025.2.0-EAP2
    ports:
      - "8024:8024"
      - "8124:8124"
    environment:
      axoniq_axonserver_hostname: axon-server
      axoniq_axonserver_autocluster_first: axon-server
      axoniq_axonserver_autocluster_contexts: _admin
    volumes:
      - ./volumes/axonserver-data:/axonserver/data
      - ./volumes/axonserver-events:/axonserver/events
  postgres:
    image: postgres:18
    environment:
      POSTGRES_DB: university_demo_db
      POSTGRES_USER: university_demo_user
      POSTGRES_PASSWORD: university_demo_password
    ports:
      - "5444:5444"
    volumes:
      - ./volumes/postgres-axon:/var/lib/postgresql/data
    command: -p 5444

volumes:
  db:
    driver: local
  data:
    driver: local
  events:
    driver: local